// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

type EmptyResult = Promise<{ data: null; error: null }>;
interface MockQueryBuilder {
  select: (_?: string) => MockQueryBuilder;
  eq: (_: string, __: unknown) => MockQueryBuilder;
  order: (_: string, __?: { ascending: boolean }) => MockQueryBuilder;
  limit: (_: number) => EmptyResult;
  single: () => EmptyResult;
  insert: (_: unknown) => EmptyResult;
  update: (_: unknown) => EmptyResult;
  upsert: (_: unknown) => EmptyResult;
}

function createMockSupabase(): SupabaseClient<Database> {
  const builder: MockQueryBuilder = {
    select: () => builder,
    eq: () => builder,
    order: () => builder,
    limit: () => Promise.resolve({ data: null, error: null }),
    single: () => Promise.resolve({ data: null, error: null }),
    insert: () => Promise.resolve({ data: null, error: null }),
    update: () => Promise.resolve({ data: null, error: null }),
    upsert: () => Promise.resolve({ data: null, error: null }),
  };
  const client = {
    from: (_table: string) => builder,
    channel: (_name: string) => ({
      on: () => client.channel(_name),
      subscribe: () => ({ id: _name }),
    }),
    removeChannel: (_ch: unknown) => undefined,
  } as unknown as SupabaseClient<Database>;
  return client;
}

export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createMockSupabase();
